@isTest //Not a test class
public class approvalQuoteLinesController { 
   /* public String quoteId {get; set;} 
    
    public List<SBQQ__QuoteLine__c> quotelines {
        get
    	{
        	return [select Id,
                    SBQQ__ListPrice__c,
                    SBQQ__Quantity__c,
                    SBQQ__ProductName__c,
                    SBQQ__ProductCode__c,
                    SBQQ__SegmentIndex__c,
                    Client_Preferred_Site__r.Name,
                    Geography__c,
                    Channel_s__c,
                    Agent_Profile__c,
                    Headcount__c,
                    AHT__c,
                    Training_Billable__c,
                    Billing_Mechanism_Final__c,
                    Fully_Loaded_EBITDA_P__c,
                    ABAY_Length__c,
                    Attrition_Production__c,
                    Seat_Utilization__c,
                    Attrition_Training__c,
                    Operations_Manager_Ratio__c,
                    Occupancy__c,
                    Trainer_Ratio__c,
                    Team_Manager_Ratio__c,
                    QA_Ratio__c,
                    Rate_Request__c
                    
                    from SBQQ__QuoteLine__c 
                    where SBQQ__ProductCode__c like 'CORE%' and SBQQ__SegmentIndex__c= null and SBQQ__Quote__c= : quoteId];
    	}
    }      */
 
}