@isTest
private class cloneQuoteControllerExtTests {
    
    /*testMethod static void testSubmit() {
        SBQQ__Quote__c quote = new SBQQ__Quote__c();
        SBQQ__Quote__c clonedQuote = new SBQQ__Quote__c();
        insert quote;
        
        Test.startTest();
        cloneQuoteControllerExt con = new cloneQuoteControllerExt(new ApexPages.StandardController(quote));
        con.onClone();
        clonedQuote = [SELECT Id,SBQQ__Source__c FROM SBQQ__Quote__c WHERE SBQQ__Source__c = :quote.Id LIMIT 1];
        Test.stopTest();
        
        System.assertEquals(quote.Id, clonedQuote.SBQQ__Source__c);
    }
        testMethod static void testCancel() {
        SBQQ__Quote__c quote = new SBQQ__Quote__c();
        SBQQ__Quote__c clonedQuote = new SBQQ__Quote__c();
        insert quote;
        
        Test.startTest();
        cloneQuoteControllerExt con = new cloneQuoteControllerExt(new ApexPages.StandardController(quote));
        con.onCancel();
        Test.stopTest();
        
    }
    testMethod static void testInit() {
        SBQQ__Quote__c quote = new SBQQ__Quote__c();
        SBQQ__Quote__c clonedQuote = new SBQQ__Quote__c();
        insert quote;
        
        Test.startTest();
        cloneQuoteControllerExt con = new cloneQuoteControllerExt(new ApexPages.StandardController(quote));
        con.onInitClone();
        Test.stopTest();
        
    }*/
}