@isTest 
private class TestApprovalTrigger {
    /*static testMethod void validateApprovalTrigger() {
        SBQQ__Quote__c testQuote1 = New SBQQ__Quote__c(); 
        insert testQuote1;
        
        sbaa__Approval__c testApproval1 = New sbaa__Approval__c();
        testApproval1.Quote__c = testQuote1.Id;
        testApproval1.sbaa__ApprovalStep__c = 10;
        testApproval1.sbaa__RecordField__c = 'Quote__c';
            
        insert testApproval1;
        
        sbaa__Approval__c testApproval2 = New sbaa__Approval__c();
        testApproval2.Quote__c = testQuote1.Id;     
        testApproval2.sbaa__ApprovalStep__c = 20;
        testApproval2.sbaa__RecordField__c = 'Quote__c';
        testApproval2.sbaa__Status__c = 'Approved';
        insert testApproval2;
        
    }*/
}